### ISSUE TITLE
Suggestion: Add an overview page

### ISSUE THREAD

**Issue by mdcarreira** [smklancher/AwairWeb#17]
It would be useful to have a page where all info could be shown, so that you don't need to scroll through all the pages on the left menu.

I was thinking about something like this:

![image](https://user-images.githubusercontent.com/23055725/191759442-b4e6b3ea-2168-4934-b82d-4bdec4b5c778.png)

Don't know if this will take a lot of work, but certainly would find it very useful :)

**Comment by smklancher** [comment]
Code needed some quality improvements first, then was able to do this.  I appreciate the separate look for the score.  But one thing to keep in mind is that the site is intended for multiple devices, so there is no single score like in your mockup.

![image](https://user-images.githubusercontent.com/2023739/192200520-b7a56fcb-b9bf-408a-9f0a-9d3af43eef97.png)

**Comment by mdcarreira** [comment]
This is awesome! Thank you for implementing this! :+1: 

I just miss a refresh button, so that you don't have to switch between left menus to get your view updated :)

**Comment by smklancher** [comment]
No problem.  But for refresh, just use your browser refresh (F5).  The webassembly of the app is already cached from first access.
